version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip bash jq
            pip install \
              awscli
      - run:
          name: Setup common environment variables
          command: |
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}"' >> $BASH_ENV
      - run:
          name: Run Tests
          command: |
            cd tests
            ./functions_test.sh
      - run:
          name: Deploy To Amazon S3 Bucket
          command: |
            aws s3 cp script.sh s3://${S3_BUCKET}/tool-a/script.sh
      - run:
          name: Deploy To Amazon ECR
          command: |
            docker build -t ${FULL_IMAGE_NAME} .
            # docker build -t testtest .
            # eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            # docker push ${FULL_IMAGE_NAME}
